### ISSUE TITLE
Support Office 2007+

### ISSUE THREAD

**Issue by kjduling** [millij/poi-object-mapper#14]
Using POI 4.0.1 and poi-object-mapper 1.0.0

Trying to load a simple xlsx sheet, no formulas or anything fancy.
```java
        XlsReader reader = new XlsReader();
        try {
            reader.read(XlsRecord.class, inputStream);
        } catch (SpreadsheetReadException e) {
            e.printStackTrace();
        }
```
produces the following error:
```io.github.millij.poi.SpreadsheetReadException: Error reading HSSFSheet, to class com.company.XlsRecord : The supplied data appears to be in the Office 2007+ XML. You are calling the part of POI that deals with OLE2 Office Documents. You need to call a different part of POI to process this data (eg XSSF instead of HSSF)```

**Comment by kjduling** [comment]
Discovered I had a naming conflict that hid poi-object-mapper's `XlsxReader` class.  Converted over to it and ran in to `java.lang.NoSuchMethodError: org.apache.poi.xssf.eventusermodel.XSSFSheetXMLHandler.<init>(Lorg/apache/poi/xssf/model/StylesTable;Lorg/apache/poi/xssf/eventusermodel/ReadOnlySharedStringsTable;Lorg/apache/poi/xssf/eventusermodel/XSSFSheetXMLHandler$SheetContentsHandler;Z)V
`

**Comment by millij** [comment]
Hi Kevin,
The current release `1.0.0` works with apache POI `3.17`.
I believe you have a hard dependency on apache POI - `4.0.1`.  
Current `poi-object-mapper` implementation doesn't work with this as POI `4.+` version at it is not backward compatible.

Is it possible for you to use POI - `3.17` version?
If you have a hard dependency on POI 4.+ and cannot switch to `3.+`, let us know, will release a **SNAPSHOT** version that supports POI `4.+`.

**Comment by millij** [comment]
@kjduling 
Are you still facing the issue? If not, can you close the issue.

**Comment by millij** [comment]
@kjduling,

Updated the implementation with apache poi `4.0.1` version in [develop](https://github.com/millij/poi-object-mapper/tree/develop) branch.
As it's not yet released, you can checkout and build from source to use it with apache poi `4.0.1`

Cheers,

**Comment by kjduling** [comment]
> @kjduling
> Are you still facing the issue? If not, can you close the issue.

No, I followed your suggestion and used 3.17.

**Comment by pkgajulapalli** [comment]
when can we expect it to be ready for poi 4.0.1 version?

**Comment by millij** [comment]
@pkgajulapalli 
Couldn't work on the release as I was busy with my full time job off late.

As I [commented earlier](https://github.com/millij/poi-object-mapper/issues/14#issuecomment-470393854), the [develop branch](https://github.com/millij/poi-object-mapper/tree/develop) is already updated with POI 4.0.1 version.
You can either build directly from develop branch or refer to the [2.0.0 pre-release](https://github.com/millij/poi-object-mapper/releases/tag/2.0.0).

Hope this works for you.
